version: "3.8"

services:
  mysqldb:
    platform: linux/arm64
    image: mysql
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 3
  app:
    depends_on:
      - mysqldb
    restart: on-failure
    image: book-service
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/$MYSQL_DATABASE
      SPRING_DATASOURCE_USERNAME: $MYSQL_USER
      SPRING_DATASOURCE_PASSWORD: $MYSQL_PASSWORD
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
